import datetime
from google.cloud.bigquery.table import Row
from google.cloud._helpers import UTC


ARTICLE_RESULT_15747 = Row(
    (
        (
            "legacy_site",
            "15747",
            "10.7554/eLife.15747",
            datetime.datetime(2016, 5, 31, 11, 31, 1, tzinfo=UTC),
            datetime.datetime(2016, 5, 31, 11, 31, 1, tzinfo=UTC),
            datetime.datetime(2016, 6, 10, 6, 28, 43, tzinfo=UTC),
            False,
            [
                {
                    "Title": "Dr.",
                    "Last_Name": "Baldwin",
                    "Middle_Name": None,
                    "Role": "Senior Editor",
                    "ORCID": None,
                    "First_Name": "Ian",
                    "Person_ID": "1013",
                },
                {
                    "Title": "",
                    "Last_Name": "Bergstrom",
                    "Middle_Name": None,
                    "Role": "Reviewing Editor",
                    "ORCID": None,
                    "First_Name": "Carl",
                    "Person_ID": "1046",
                },
            ],
        )
    ),
    {
        "Source_Site_ID": 0,
        "Manuscript_ID": 1,
        "DOI": 2,
        "Review_Comment_UTC_Timestamp": 3,
        "Editor_Evaluation_UTC_Timestamp": 4,
        "Author_Response_UTC_Timestamp": 5,
        "Is_Accepted": 6,
        "Reviewers_And_Editors": 7,
    },
)

ARTICLE_RESULT_84364 = Row(
    (
        (
            "legacy_site",
            "84364",
            "10.7554/eLife.84364",
            datetime.datetime(2023, 2, 13, 11, 31, 1, tzinfo=UTC),
            datetime.datetime(2023, 2, 13, 11, 31, 1, tzinfo=UTC),
            datetime.datetime(2023, 2, 10, 6, 28, 43, tzinfo=UTC),
            False,
            [
                {
                    "Title": "Dr.",
                    "Last_Name": "Eisen",
                    "Middle_Name": "B",
                    "Role": "Reviewing Editor",
                    "ORCID": "test-orcid",
                    "First_Name": "Michael",
                    "Person_ID": "1013",
                },
            ],
        )
    ),
    {
        "Source_Site_ID": 0,
        "Manuscript_ID": 1,
        "DOI": 2,
        "Review_Comment_UTC_Timestamp": 3,
        "Editor_Evaluation_UTC_Timestamp": 4,
        "Author_Response_UTC_Timestamp": 5,
        "Is_Accepted": 6,
        "Reviewers_And_Editors": 7,
    },
)

PREPRINT_95901_V1_DATA_AVAILABILITY_RESULT = Row(
    (
        "95901",
        "1",
        "eLife-RP-RA-2023-89331R2",
        "<xml>\n  <data_availability_textbox>Sequencing data (fastq) is available in the Sequence Read Archive (SRA) with the BioProject identification PRJNA934938.  \n\nScripts used for ChIP-seq, RNA-seq, and VSG-seq analysis are available at https://github.com/cestari-lab/lab_scripts. \n\nA specific pipeline was developed for clonal VSG-seq analysis, available at https://github.com/cestari-lab/VSG-Bar-seq.</data_availability_textbox>\n  <datasets>\n    <dataset>\n      <seq_no>1</seq_no>\n      <authors_text_list>Touray AO, Rajesh R, Isebe I, Sternlieb T, Loock M, Kutova O, Cestari I</authors_text_list>\n      <id>https://dataview.ncbi.nlm.nih.gov/object/PRJNA934938</id>\n      <license_info>SRA Bioproject PRJNA934938</license_info>\n      <title>Trypanosoma brucei brucei strain:Lister 427 DNA or RNA sequencing</title>\n      <year>2023</year>\n    </dataset>\n    <datasets_ind>1</datasets_ind>\n    <dryad_ind>0</dryad_ind>\n    <reporting_standards_ind>0</reporting_standards_ind>\n  </datasets>\n  <prev_published_datasets>\n    <dataset>\n      <seq_no>1</seq_no>\n      <authors_text_list>B. Akiyoshi, K. Gull</authors_text_list>\n      <id>https://www.ncbi.nlm.nih.gov/sra/?term=SRP031518</id>\n      <license_info>SRA, accession numbers SRR1023669\tand SRX372731</license_info>\n      <title>Trypanosoma brucei KKT2 ChIP</title>\n      <year>2014</year>\n    </dataset>\n    <datasets_ind>1</datasets_ind>\n    <dryad_ind>0</dryad_ind>\n  </prev_published_datasets>\n</xml>",
    ),
    {
        "manuscript_id": 0,
        "manuscript_version_str": 1,
        "long_manuscript_identifier": 2,
        "data_availability_xml": 3,
    },
)

# based on data from 106814v1
PREPRINT_95901_V1_FUNDING_RESULT = [
    Row(
        (
            "95901",
            "1",
            55759,
            "Igor  Kramnik",
            "100000050",
            "HHS | NIH | National Heart, Lung, and Blood Institute (NHLBI)",
            1,
            "R01HL126066",
            "eLife-RP-RA-RC-2025-106814",
        ),
        {
            "manuscript_id": 0,
            "manuscript_version_str": 1,
            "author_id": 2,
            "author_name": 3,
            "crossref_funder_id": 4,
            "funder": 5,
            "funding_order_number": 6,
            "grant_reference_id": 7,
            "long_manuscript_identifier": 8,
        },
    ),
    Row(
        (
            "95901",
            "1",
            55759,
            "Igor  Kramnik",
            "100000050",
            "HHS | NIH | National Heart, Lung, and Blood Institute (NHLBI)",
            2,
            "R01HL133190",
            "eLife-RP-RA-RC-2025-106814",
        ),
        {
            "manuscript_id": 0,
            "manuscript_version_str": 1,
            "author_id": 2,
            "author_name": 3,
            "crossref_funder_id": 4,
            "funder": 5,
            "funding_order_number": 6,
            "grant_reference_id": 7,
            "long_manuscript_identifier": 8,
        },
    ),
    Row(
        (
            "95901",
            "1",
            13262,
            "Boris N Kholodenko",
            "100000054",
            "HHS | NIH | National Cancer Institute (NCI)",
            3,
            "R01CA244660",
            "eLife-RP-RA-RC-2025-106814",
        ),
        {
            "manuscript_id": 0,
            "manuscript_version_str": 1,
            "author_id": 2,
            "author_name": 3,
            "crossref_funder_id": 4,
            "funder": 5,
            "funding_order_number": 6,
            "grant_reference_id": 7,
            "long_manuscript_identifier": 8,
        },
    ),
    Row(
        (
            "95901",
            "1",
            13262,
            "Boris N Kholodenko",
            "",
            "EU Grant",
            4,
            "101136926 MULTIR",
            "eLife-RP-RA-RC-2025-106814",
        ),
        {
            "manuscript_id": 0,
            "manuscript_version_str": 1,
            "author_id": 2,
            "author_name": 3,
            "crossref_funder_id": 4,
            "funder": 5,
            "funding_order_number": 6,
            "grant_reference_id": 7,
            "long_manuscript_identifier": 8,
        },
    ),
    Row(
        (
            "95901",
            "1",
            30828,
            "Nelson C. Lau",
            "100000049",
            "HHS | NIH | National Institute on Aging (NIA)",
            6,
            "R01-AG052465",
            "eLife-RP-RA-RC-2025-106814",
        ),
        {
            "manuscript_id": 0,
            "manuscript_version_str": 1,
            "author_id": 2,
            "author_name": 3,
            "crossref_funder_id": 4,
            "funder": 5,
            "funding_order_number": 6,
            "grant_reference_id": 7,
            "long_manuscript_identifier": 8,
        },
    ),
    Row(
        (
            "95901",
            "1",
            30828,
            "Nelson C. Lau",
            "100000057",
            "HHS | NIH | National Institute of General Medical Sciences (NIGMS)",
            7,
            "R01-GM135215",
            "eLife-RP-RA-RC-2025-106814",
        ),
        {
            "manuscript_id": 0,
            "manuscript_version_str": 1,
            "author_id": 2,
            "author_name": 3,
            "crossref_funder_id": 4,
            "funder": 5,
            "funding_order_number": 6,
            "grant_reference_id": 7,
            "long_manuscript_identifier": 8,
        },
    ),
]

PREPRINT_95901_V1_AUTHOR_DETAILS_RESULT = [
    Row(
        (
            "95901",
            "1",
            "eLife-RP-RA-2024-95901",
            [
                {
                    "person_id": "351476",
                    "name": "Wuxiang Xie",
                    "title": None,
                    "first_name": "Wuxiang",
                    "middle_name": None,
                    "last_name": "Xie",
                    "position": 6,
                    "is_corresponding_author": False,
                    "ORCID": None,
                },
                {
                    "person_id": "351475",
                    "name": "Yongqian Wang",
                    "title": None,
                    "first_name": "Yongqian",
                    "middle_name": None,
                    "last_name": "Wang",
                    "position": 5,
                    "is_corresponding_author": False,
                    "ORCID": None,
                },
                {
                    "person_id": "351474",
                    "name": "Darui Gao",
                    "title": None,
                    "first_name": "Darui",
                    "middle_name": None,
                    "last_name": "Gao",
                    "position": 4,
                    "is_corresponding_author": False,
                    "ORCID": None,
                },
                {
                    "person_id": "351473",
                    "name": "Wenya Zhang",
                    "title": None,
                    "first_name": "Wenya",
                    "middle_name": None,
                    "last_name": "Zhang",
                    "position": 3,
                    "is_corresponding_author": False,
                    "ORCID": None,
                },
                {
                    "person_id": "351477",
                    "name": "Fanfan Zheng",
                    "title": None,
                    "first_name": "Fanfan",
                    "middle_name": None,
                    "last_name": "Zheng",
                    "position": 7,
                    "is_corresponding_author": True,
                    "ORCID": "0000-0003-2767-2600",
                },
                {
                    "person_id": "351472",
                    "name": "Yang Pan",
                    "title": None,
                    "first_name": "Yang",
                    "middle_name": None,
                    "last_name": "Pan",
                    "position": 2,
                    "is_corresponding_author": False,
                    "ORCID": "0000-0000-0000-0000",
                },
                {
                    "person_id": "351447",
                    "name": "Jie Liang",
                    "title": "Ms.",
                    "first_name": "Jie",
                    "middle_name": None,
                    "last_name": "Liang",
                    "position": 1,
                    "is_corresponding_author": False,
                    "ORCID": "0000-0002-3613-8488",
                },
            ],
        ),
        {
            "manuscript_id": 0,
            "manuscript_version_str": 1,
            "long_manuscript_identifier": 2,
            "author_details": 3,
        },
    )
]
